# Generated by Django 4.2.7 on 2023-12-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartcube_api", "0002_alter_product_brand_alter_product_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="path",
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="product",
            name="ratings",
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
