# Generated by Django 4.2.7 on 2023-12-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartcube_api", "0003_remove_product_path_alter_product_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="inStock",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="product",
            name="ratings",
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
