# Generated by Django 4.2.7 on 2023-12-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartcube_api", "0005_remove_cartitem_price_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="isPaid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="shopuser",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
