# Generated by Django 4.2.7 on 2023-12-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartcube_api", "0006_cart_ispaid_alter_shopuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
