# Generated by Django 4.2.7 on 2023-12-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartcube_api", "0007_alter_shopuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
