# Generated by Django 4.2.7 on 2023-12-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("smartcube_api", "0008_alter_shopuser_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="isPaid",
        ),
    ]
