# Generated by Django 4.2.7 on 2023-12-06 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("smartcube_api", "0010_remove_cart_user_cartitem_user_delete_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="date",
            new_name="ctreate_at",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="user",
        ),
    ]
