# Generated by Django 4.2.7 on 2023-12-07 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("smartcube_api", "0013_cart_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="user",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
