# Generated by Django 4.2.7 on 2023-12-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("smartcube_api", "0014_remove_cart_user_cartitem_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="user",
        ),
    ]
