# Generated by Django 4.2.7 on 2023-12-07 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("smartcube_api", "0016_rename_ctreate_at_cart_ctreated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="ctreated_at",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="user",
        ),
        migrations.AddField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
