# Generated by Django 4.2.7 on 2023-12-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartcube_api", "0018_alter_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
