# Generated by Django 4.2.7 on 2023-12-07 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("smartcube_api", "0020_remove_cart_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="updated_at",
        ),
    ]
