# Generated by Django 4.2.7 on 2023-12-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("smartcube_api", "0021_remove_cart_updated_at"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShopUser",
            new_name="Customer",
        ),
        migrations.AddField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(
                through="smartcube_api.CartItem", to="smartcube_api.product"
            ),
        ),
    ]
