# Generated by Django 4.2.7 on 2023-12-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartcube_api", "0024_cart_cart_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="inStock",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
