# Generated by Django 4.2.7 on 2023-12-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("smartcube_api", "0025_alter_product_instock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="inStock",
        ),
    ]
