# Generated by Django 4.2.7 on 2023-12-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartcube_api", "0026_remove_product_instock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="inStock",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
